#lang racket

;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


(define (f i j the-sum)
  (if (< j 4000001)     
      (f j (+ i j)(if (zero? (modulo j 2))
                      (+ the-sum j) the-sum) )
      the-sum)  
  )  

(f 1 2 0)

